### ISSUE TITLE
Cannot extract package grunt-cli

### ISSUE THREAD

**Issue by dottodot** [alterx/sailsjs-nodewebkit#1]
Just out of curiosity have you come across the error Cannot extract package and in reference to the grunt-cli package, as I'm unable to get my sails app working with node webkit because of this.

**Comment by alterx** [comment]
Hmmm, interesting. I've never had that issue. Are you using this repo as a base or just trying on another project?

**Comment by dottodot** [comment]
I'm was having the problem on my app, but I tried this repo and got the same error.

**Comment by alterx** [comment]
Ok @dottodot , I'll look into it. Could you please provide some details about the steps to reproduce and the outcome you're getting?

**Comment by dottodot** [comment]
OK I've tried on a fresh test app, replacing the app.js file with yours, adding the spash.hml, and adjusting the package.json. I've run sails lift just to check it works as expected and then I've used https://github.com/mllrsohn/node-webkit-builder i.e. nwbuild -r pathtoapp/

this then gives the error as per the image below

![screen shot 2015-01-29 at 10 00 20](https://cloud.githubusercontent.com/assets/811652/5955723/bfe6d0a8-a79d-11e4-9401-d1ccb0fbb707.png)

The app does also seem to load ok behind the error window.

However if I then build the app using gulp, when I open it I get no error but it just doesn't load and I get a white screen.

Hope that makes sense.

**Comment by alterx** [comment]
Sure, as soon as I get home i'll see if I can replicate this. 
I'll keep you posted.

**Comment by alterx** [comment]
Hey @dottodot , I've been really sick but I'm back into business. Couldn't really replicate your issue but I updated the code to work with the latest version on node-webkit (now called nwjs). Please let me know if you continue to have this issue. 
Also, are you working on a machine that has windows installed? 
If so, that might be it, you know that the node_modules folder tends to become HUGE.

**Comment by senica** [comment]
Just wanted to report that the issue still exists. This is on OSX 10.9.1. Pretty much the same issue. I haven't looked into it yet, but if find something, I'll add a pull request.

![screen shot 2015-03-23 at 11 14 50 am](https://cloud.githubusercontent.com/assets/954952/6787162/3050e228-d14e-11e4-97b3-98db3969a45a.png)

**Comment by alterx** [comment]
@senica I was able to replicate (finally!)
For some reason I was missing all the grunt config files in this repo, I added the missing files and the grunt error is gone for good.

Could you please confirm that my latest commit fixes the issue ? OSX 10.10 here

**Comment by senica** [comment]
@alterx Issue still exists with commit a84ec3c0045521d3470553d7f0ef2c8a3e1865eb . I was first getting an error about pipeline.js missing. I added one in the tasks directory from another project and sails would run fine, but node-webkit still gave me the same error regarding grunt.

**Comment by alterx** [comment]
This is really weird @senica , I can't replicate it. Just cloned a fresh copy of the repo and ran it using 'nwbuild -r /sailsjs-webkit' with no issues. This on a Win7 machine @ work. Also, I ran it yesterday on my personal macbookpro, with no issues.

Both are running the latest versions of nw.js (it was renamed from node-webkit after they started using io.js) and nwbuilder [https://github.com/mllrsohn/node-webkit-builder]

**Comment by senica** [comment]
That's a bummer. Well, I seriously doubt this is helpful in anyway but: https://youtu.be/9DJu0n_ar90

**Comment by alterx** [comment]
I've been able to replicate again an tracked down the issue to the sails version in the package.json file.
Apparently the version provided ^0.10.5 was breaking the app. I replicated and suppressed the error by changing the version. I'll dig a bit more into it but updating to the latest version seems to fix the issue.
